name: publish

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.9'
    secrets:
      token:
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: "poetry"

      - name: Configure credentials to access PyPI
        run: |
          poetry config pypi-token.pypi "${{ secrets.token }}"

      - name: build package
        run: |
          poetry build

      - name: Release
        run: |
          poetry publish